version: '3.8'
services:
  postgres:
    image: postgres:15.5
    container_name: eventmate_db
    environment:
      POSTGRES_DB: eventmate
      POSTGRES_USER: eventmate_user
      POSTGRES_PASSWORD: eventmate_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventmate_user -d eventmate"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
